FROM debian:unstable

RUN apt-get update && apt-get install -y --no-install-recommends \
	bash \
	vim \
	git \
	gitk \
	git-buildpackage \
	ssh \
	gdb \
	less \
	build-essential

RUN apt-get update && apt-get install -y --no-install-recommends \
	debhelper \
	dh-autoreconf \
	autoconf \
	automake \
	autotools-dev \
	libncurses5-dev \
	gperf \
	bison \
	flex \
	texinfo \
	help2man \
	gawk \
	wget \
	git \
	subversion \
	bzip2 \
	libtool-bin